wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = true
idle = true
frame = "none"
title-hidden = true
tabs = true

[font]
normal = ["RecMonoLinear Nerd Font"]
bold = ["RecMonoLinear Nerd Font"]
italic = ["RecMonoLinear Nerd Font"]
bold_italic = ["RecMonoLinear Nerd Font"]
size = 16
